import type { ScoutRepository } from "@/lib/types";

export const sampleRepositories: ScoutRepository[] = [
  {
    name: "chaincraft",
    owner: "sample-labs",
    fullName: "sample-labs/chaincraft",
    description: "Composable TypeScript toolkit for building onchain app workflows and wallet actions.",
    url: "",
    stars: 184,
    forks: 21,
    openIssues: 18,
    createdAt: "2025-10-14T12:00:00Z",
    updatedAt: "2026-05-28T09:20:00Z",
    topics: ["web3", "wallet", "developer-tools", "typescript"],
    language: "TypeScript",
    license: "MIT",
    category: "wallet developer tools",
    signals: {
      goodFirstIssueCount: 4,
      helpWantedCount: 3,
      hasContributing: true,
      hasDocsFolder: true,
      readmeQuality: "basic",
      issueActivity: "active",
      isFresh: true,
      localizationOpportunity: true,
    },
  },
  {
    name: "agent-mesh-kit",
    owner: "sample-ai",
    fullName: "sample-ai/agent-mesh-kit",
    description: "Small framework for coordinating LLM tool calls across local and hosted agent runtimes.",
    url: "",
    stars: 427,
    forks: 38,
    openIssues: 31,
    createdAt: "2025-07-03T08:00:00Z",
    updatedAt: "2026-05-30T18:30:00Z",
    topics: ["ai-agents", "llm-tools", "developer-tools", "python"],
    language: "Python",
    license: "Apache-2.0",
    category: "AI agent infrastructure",
    signals: {
      goodFirstIssueCount: 5,
      helpWantedCount: 7,
      hasContributing: false,
      hasDocsFolder: true,
      readmeQuality: "strong",
      issueActivity: "active",
      isFresh: true,
      localizationOpportunity: true,
    },
  },
  {
    name: "zk-lab-notes",
    owner: "proofgarden",
    fullName: "proofgarden/zk-lab-notes",
    description: "Educational zero-knowledge examples and lightweight proving experiments for app developers.",
    url: "",
    stars: 96,
    forks: 13,
    openIssues: 9,
    createdAt: "2026-01-18T10:00:00Z",
    updatedAt: "2026-05-22T13:15:00Z",
    topics: ["zk", "cryptography", "education", "rust"],
    language: "Rust",
    license: "MIT",
    category: "ZK education",
    signals: {
      goodFirstIssueCount: 2,
      helpWantedCount: 2,
      hasContributing: false,
      hasDocsFolder: false,
      readmeQuality: "thin",
      issueActivity: "warming",
      isFresh: true,
      localizationOpportunity: true,
    },
  },
  {
    name: "defi-risk-sim",
    owner: "open-vaults",
    fullName: "open-vaults/defi-risk-sim",
    description: "Scenario simulator for DeFi vault parameters, liquidation assumptions, and pool risk.",
    url: "",
    stars: 812,
    forks: 74,
    openIssues: 14,
    createdAt: "2024-11-09T11:30:00Z",
    updatedAt: "2026-05-11T16:50:00Z",
    topics: ["defi", "risk", "simulation", "crypto-infrastructure"],
    language: "Go",
    license: "BSD-3-Clause",
    category: "DeFi infrastructure",
    signals: {
      goodFirstIssueCount: 1,
      helpWantedCount: 5,
      hasContributing: true,
      hasDocsFolder: false,
      readmeQuality: "basic",
      issueActivity: "active",
      isFresh: true,
      localizationOpportunity: false,
    },
  },
  {
    name: "prompt-ledger",
    owner: "smallstack",
    fullName: "smallstack/prompt-ledger",
    description: "Versioned prompt evaluation ledger for LLM products, with simple review workflows.",
    url: "",
    stars: 138,
    forks: 12,
    openIssues: 7,
    createdAt: "2025-12-02T07:45:00Z",
    updatedAt: "2026-05-24T20:10:00Z",
    topics: ["llm-tools", "evals", "developer-tools"],
    language: "TypeScript",
    license: "MIT",
    category: "LLM tooling",
    signals: {
      goodFirstIssueCount: 0,
      helpWantedCount: 3,
      hasContributing: false,
      hasDocsFolder: true,
      readmeQuality: "thin",
      issueActivity: "warming",
      isFresh: true,
      localizationOpportunity: true,
    },
  },
];
